// <auto-generated />
using BSolidarioAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BSolidarioAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221119173318_SecondMigrationv2F4")]
    partial class SecondMigrationv2F4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("BSolidarioAPI.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("document_number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("BSolidarioAPI.Models.ClientPlanType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int>("PlanTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("annual_interested")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("montly_interested")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("PlanTypeId");

                    b.ToTable("ClientPlanTypes");
                });

            modelBuilder.Entity("BSolidarioAPI.Models.PlanType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PlanType");
                });

            modelBuilder.Entity("BSolidarioAPI.Models.ClientPlanType", b =>
                {
                    b.HasOne("BSolidarioAPI.Models.Client", "Client")
                        .WithMany("ClientsPlanType")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BSolidarioAPI.Models.PlanType", "PlanType")
                        .WithMany("ClientsPlanType")
                        .HasForeignKey("PlanTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("PlanType");
                });

            modelBuilder.Entity("BSolidarioAPI.Models.Client", b =>
                {
                    b.Navigation("ClientsPlanType");
                });

            modelBuilder.Entity("BSolidarioAPI.Models.PlanType", b =>
                {
                    b.Navigation("ClientsPlanType");
                });
#pragma warning restore 612, 618
        }
    }
}
